spring.application.name=meuprojeto

# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Rejeita JSONs com campos que não existem na classe Java (retorna HTTP 400 Bad Request)
spring.jackson.deserialization.fail-on-unknown-properties=true

# Dá erro se o JSON de um POST vier com campos faltando
spring.jackson.deserialization.fail-on-missing-creator-properties=true

# criar e modificar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# mostrar o sql que o JPA inventa
spring.jpa.show-sql=true

# formatar bonitinho o sql?
spring.jpa.properties.hibernate.format_sql=true

# preciso disso ligado pra executar o data.sql que vou botar
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Log do MVC Spring
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=TRACE
logging.level.com.fasterxml.jackson=TRACE