spring.application.name=meuprojeto

# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# criar e modificar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# mostrar o sql que o JPA inventa
spring.jpa.show-sql=true

# formatar bonitinho o sql?
spring.jpa.properties.hibernate.format_sql=true

# preciso disso ligado pra executar o data.sql que vou botar
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always